spring:
  # OAuth2
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: ${K_ID}
            client-secret: ${K_SECRET}
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email

          google:
            client-name: google
            client-id: ${G_ID}
            client-secret: ${G_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

